# Generated by Django 3.2.5 on 2021-07-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womens_health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_date', models.DateField(blank=True, null=True)),
                ('period_end_date', models.DateField(blank=True, null=True)),
                ('ovulation_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
