# Generated by Django 3.2.5 on 2021-07-23 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('womens_health', '0002_generatedcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcycle',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='women_cycle', to='womens_health.womencycle'),
            preserve_default=False,
        ),
    ]
