# Generated by Django 3.2.5 on 2021-07-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('womens_health', '0003_generatedcycle_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedcycle',
            name='account',
        ),
    ]
