# Generated by Django 3.2.5 on 2021-07-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womens_health', '0004_remove_generatedcycle_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedcycle',
            old_name='ovulation_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='generatedcycle',
            name='period_end_date',
        ),
        migrations.RemoveField(
            model_name='generatedcycle',
            name='period_start_date',
        ),
        migrations.AddField(
            model_name='generatedcycle',
            name='event',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
